### ISSUE TITLE
build failure on NetBSD

### ISSUE THREAD

**Issue by 0323pin** [tui-lipan/rozi#3]
Hi,

pkgsrc/NetBSD maintainer here ...

I know the `README.md` says:
> A modern tiling terminal multiplexer for Linux, macOS, and Windows. 

But, I don't think it would be to much of a stretch to support *BSD also by considering variants of `errno` exposure.

Currently, compiling `rozi` within the pkgsrc-infrastructure fails with:

```
error[E0425]: cannot find function `__error` in crate `libc`
   --> src/platform/cursor.rs:57:24
    |
 57 |         unsafe { libc::__error() }
    |                        ^^^^^^^
    |
   ::: /usr/pkgsrc/wip/rozi/work/vendor/libc-0.2.189/src/unix/bsd/netbsdlike/mod.rs:723:5
    |
723 |     pub fn __errno() -> *mut c_int;
    |     ------------------------------- similarly named function `__errno` defined here
    |
help: a function with a similar name exists
    |
 57 -         unsafe { libc::__error() }
 57 +         unsafe { libc::__errno() }
    |

error[E0425]: cannot find function `__error` in crate `libc`
   --> src/platform/server_lifecycle.rs:144:24
    |
144 |         unsafe { libc::__error() }
    |                        ^^^^^^^
    |
   ::: /usr/pkgsrc/wip/rozi/work/vendor/libc-0.2.189/src/unix/bsd/netbsdlike/mod.rs:723:5
    |
723 |     pub fn __errno() -> *mut c_int;
    |     ------------------------------- similarly named function `__errno` defined here
    |
help: a function with a similar name exists
    |
144 -         unsafe { libc::__error() }
144 +         unsafe { libc::__errno() }
    |
```

Would you be able/willing to add support for other OSs?

**Comment by Razuer** [comment]
Yeah, that one's on me. I wrote the errno accessor as "Linux, or else macOS" and never thought about the rest of the BSDs, so `not(target_os = "linux")` happily lands on `__error` for NetBSD. Two lines, both in `src/platform/`. I'll push a fix.

As for supporting other OSs: I have no NetBSD machine and no CI for it, so I can't promise it stays green on its own. What I can do is keep the code honest about which platform it's on, take patches like this, and add NetBSD to the README once you tell me a build actually works end to end. That seems more useful than claiming support I can't verify.

One question before I push. Do those two errors stop the build, or does it keep going and hit more after them? If there's a longer list I'd rather fix it all at once than have you come back here three times.

**Comment by Razuer** [comment]
Answered my own question, so you don't have to.

Fixed on master. The mapping now lives in one place and lists the accessors explicitly: `__errno_location` on Linux and Hurd, `__errno` on Android and the NetBSD-likes, `__error` on Apple, FreeBSD and DragonFly, `___errno` on Solaris and illumos. A target nobody has listed now fails with a `compile_error!` naming all four, rather than quietly falling into a default arm and picking the wrong one, which is how this got past me in the first place.

I set up a cross-compile here to check it, since cross-rs publishes a NetBSD image and that beat building a toolchain. Against `x86_64-unknown-netbsd`, `cargo check` goes all the way through and clippy with `-D warnings` is clean, tests and benches included. So those two were the only compile errors. Nothing else is waiting behind them.

What that does not tell either of us is whether it runs. Cross-compiling proves it links, and rozi leans on ptys, signals and Unix sockets hard enough that I'd expect NetBSD to have some opinions about it. If you get it to start, I'd genuinely like to hear what happens, good or bad.

Leaving this open until you've had a chance to build it. I'll add a NetBSD cross-check to CI so it doesn't quietly rot again.

**Comment by 0323pin** [comment]
Thanks for the investigation and report. Unfortunately, it has been a lot at work today but, tomorrow I should have sometime to test it on bare metal x86_64 only.

**Comment by 0323pin** [comment]
Hi,

I think the following says more than any wording ...

<img width="1366" height="768" alt="Image" src="https://github.com/user-attachments/assets/951be684-22d6-4993-808f-001f06f7c116" />

<img width="1366" height="768" alt="Image" src="https://github.com/user-attachments/assets/bd556fd8-e7fc-4633-b1bd-18221b99c0a3" />

I'll play with it for a while to understand it a bit better but, hey ... it works!

**Comment by Razuer** [comment]
Glad it works! The official release is coming soon. Until then, I still have plenty of improvements and fixes planned. After that, I’ll try to put together a tutorial as well ;)

**Comment by 0323pin** [comment]
> Glad it works! The official release is coming soon. Until then, I still have plenty of improvements and fixes planned. After that, I’ll try to put together a tutorial as well ;)

I can push a package for v0.0.18 pulling the sources from tha git-hash

**Comment by 0-wiz-0** [comment]
Just FYI: you can build natively in NetBSD too, see https://github.com/vmactions/netbsd-vm

Here's an example of a C project doing that:
https://github.com/nih-at/libzip/blob/main/.github/workflows/bsd.yml

**Comment by 0323pin** [comment]
@Razuer I've now merged a package for `v0.0.18`, [commit log](https://mail-index.netbsd.org/pkgsrc-changes/2026/09/12/msg354456.html) for your reference

**Comment by Razuer** [comment]
@0-wiz-0 thanks, that beats the cross-compile I settled for. CI now boots a NetBSD VM and runs the test suite in it, so we find out whether it actually runs and not just whether it links. It is non-gating for now, since nobody here has a NetBSD box to debug a red run on, but at least it will say something when it breaks.

@0323pin thanks for packaging it. The docs now say NetBSD builds and runs, with pkgsrc as the way to install it there, and `rozi update` recognises `/usr/pkg` so it points at pkgsrc instead of calling the install unmanaged.

Both are on a branch for now and will land on master shortly.

---
_Generated by [Claude Code](https://claude.ai/code)_

**Comment by 0-wiz-0** [comment]
I commented on two possible problems with the CI action.
